services:
  reverse-proxy:
    image: caddy:2.8-alpine
    container_name: erpjir-reverse-proxy
    depends_on:
      frontend:
        condition: service_started
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME:-localhost}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
